{{ $dpg := .Values.deployment.pixiuGateway }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixiu-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: pixiu-gateway
  {{- include "pg.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: pixiu-gateway
    {{- include "pg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: pixiu-gateway
      {{- include "pg.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.pod.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: pixiu-gateway-sa
      containers:
        {{- with $dpg.image }}
        - name: pixiu-gateway
          image: {{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .imagePullPolicy }}
        {{- end }}
          command:
            - /usr/local/bin/pg-controller
          args:
            - --config-path=/config/pg.yaml
            - --log-level=info
          ports:
          {{- with $dpg.ports }}
            - containerPort: {{ .healthContainerPort }}
              name: health
              protocol: {{ .protocol }}
            - containerPort: {{ .metricsContainerPort }}
              name: metrics
              protocol: {{ .protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
          {{- toYaml $dpg.resources | nindent 12 }}